[versions]
compileSdk = "36"
minSdk = "23"
targetSdk = "36"

protobufJava = "3.25.8"
slf4jHandroid = "2.0.13"

[libraries]
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
slf4j-handroid = { module = "com.gitlab.mvysny.slf4j:slf4j-handroid", version.ref = "slf4jHandroid" }

[plugins]
